# Generated by Django 2.2 on 2020-06-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200608_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ame', models.CharField(max_length=200, null=True)),
                ('posterImage', models.ImageField(blank=True, null=True, upload_to='image')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product')),
            ],
        ),
    ]
