# Generated by Django 2.2 on 2020-06-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_adposter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adposter',
            old_name='ame',
            new_name='name',
        ),
    ]
