# Generated by Django 2.1.15 on 2020-06-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
