# Generated by Django 2.1.15 on 2020-06-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
